Feature/dev 434 message content
nmshd/bkb-libraries pull request #73
Opened 2023-01-06 15:22 UTC by JLSRKonk

2023-01-09 09:38 UTC, tnotheis requested changes

2023-01-09 09:38 UTC, tnotheis commented on BuildingBlocks.Infrastructure/BuildingBlocks.Infrastructure/Persistence/BlobStorage/GoogleCloudStorage/GoogleCloudStorage.cs
> +                }
You can simplify this using Linq:

```suggestion
                var blobs = await _storageClient
                    .ListObjectsAsync(_bucketName)
                    .Select(storageObject => storageObject.Name)
                    .ToListAsync();
```

(you need to install the NuGet package System.Interactive.Async for this to compile)

2023-01-09 09:38 UTC, tnotheis commented on BuildingBlocks.Infrastructure/BuildingBlocks.Infrastructure/Persistence/BlobStorage/GoogleCloudStorage/GoogleCloudStorage.cs
> +        public async Task<IEnumerable<string>> FindAllAsync()
I'm sorry for not seeing this ealier, but I think you should return an IAsyncEnumerable. This will probably improve performance a lot when using it e.g. for the sanity checks. Unfortunately, you need to create another PR for the Application Abstractions in order to implement it.

2023-01-09 09:38 UTC, tnotheis commented on BuildingBlocks.Infrastructure/BuildingBlocks.Infrastructure/Persistence/BlobStorage/GoogleCloudStorage/GoogleCloudStorage.cs
> +                }
If you return IAsyncEnumerable, you have to change it as follows, of course:

```suggestion
                var blobs = _storageClient
                    .ListObjectsAsync(_bucketName)
                    .Select(storageObject => storageObject.Name);
```

2023-01-09 09:38 UTC, tnotheis commented on BuildingBlocks.Infrastructure/BuildingBlocks.Infrastructure/Persistence/BlobStorage/AzureStorageAccount/AzureStorageAccount.cs
> +        public async Task<IEnumerable<string>> FindAllAsync()
See comments in GoogleCloudStorage.cs

2023-01-09 09:38 UTC, tnotheis commented on BuildingBlocks.Infrastructure/BuildingBlocks.Infrastructure/Persistence/BlobStorage/GoogleCloudStorage/GoogleCloudStorage.cs
> +                _logger.LogTrace($"Found all blobs.");
Remove the `$`

2023-01-09 09:38 UTC, tnotheis commented on BuildingBlocks.Infrastructure/BuildingBlocks.Infrastructure/Persistence/BlobStorage/GoogleCloudStorage/GoogleCloudStorage.cs
> +                _logger.LogError($"There was an error listing all the blobs.", ex);
Remove the `$`

2023-01-09 09:38 UTC, tnotheis commented on BuildingBlocks.Infrastructure/BuildingBlocks.Infrastructure/Persistence/BlobStorage/GoogleCloudStorage/GoogleCloudStorage.cs
> +            _logger.LogTrace($"Listing all blobs...");
Remove the `$`

2023-01-09 09:38 UTC, tnotheis commented on BuildingBlocks.Infrastructure/BuildingBlocks.Infrastructure.Tests/Tests/GoogleCloudStorageTests.cs
> +
Write a test for when no blob exists to make sure an empty collection is returned.

2023-01-10 11:50 UTC, tnotheis commented
After merging the main branch we're good to go.

2023-01-10 11:54 UTC, daniel-almeida-konkconsulting approved these changes

2023-01-10 11:55 UTC, tnotheis approved these changes

2023-01-10 11:56 UTC, merged